spring.application.name=ticket_sale_ddd

spring.datasource.url=${CONNECTION_STRING}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=${DRIVER}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
spring.jpa.database-platform=${DIALECT}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=${CONTEXTUAL_CREATION}





